import { useState } from 'react';
import toast from 'react-hot-toast';
import { Upload, FileSpreadsheet, Check, AlertTriangle } from 'lucide-react';
import Modal from '../../components/ui/Modal';
import Button from '../../components/ui/Button';
import { createProperty } from '../../hooks/useProperties';

/** Small quote-aware CSV parser - handles the manifest.csv format (and any hand-edited variant) without needing a library. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { inQuotes = false; }
      } else {
        field += char;
      }
    } else if (char === '"') {
      inQuotes = true;
    } else if (char === ',') {
      row.push(field); field = '';
    } else if (char === '\n') {
      row.push(field); field = ''; rows.push(row); row = [];
    } else if (char !== '\r') {
      field += char;
    }
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  if (!rows.length) return [];

  const headers = rows[0].map((h) => h.trim());
  return rows.slice(1).filter((r) => r.some((cell) => cell.trim())).map((r) => {
    const obj = {};
    headers.forEach((h, idx) => { obj[h] = (r[idx] || '').trim(); });
    return obj;
  });
}

/** Maps a manifest.csv row to the fields our Property model actually uses. */
function mapRowToProperty(row) {
  const name = row.society || row.newName || row.originalName || '';
  return {
    name,
    location: row.sector || '',
    propertyType: row.configuration || '',
    furnishing: row.furnishing || '',
    priceRange: row.price || '',
    description: row.folderPath ? `Imported from folder: ${row.folderPath}` : '',
  };
}

export default function BulkImportModal({ open, onClose, onImported }) {
  const [rows, setRows] = useState([]);
  const [fileName, setFileName] = useState('');
  const [importing, setImporting] = useState(false);
  const [progress, setProgress] = useState(0);

  const handleFile = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      const parsed = parseCsv(String(reader.result));
      setRows(parsed.map(mapRowToProperty));
    };
    reader.readAsText(file);
  };

  const validRows = rows.filter((r) => r.name);
  const skippedCount = rows.length - validRows.length;

  const handleImport = async () => {
    setImporting(true);
    setProgress(0);
    let success = 0;
    for (let i = 0; i < validRows.length; i++) {
      try {
        await createProperty(validRows[i]);
        success += 1;
      } catch {
        // one bad row shouldn't stop the rest
      }
      setProgress(i + 1);
      await new Promise((r) => setTimeout(r, 300)); // gentle pacing for the Sheets API
    }
    setImporting(false);
    toast.success(`Imported ${success} of ${validRows.length} properties.`);
    onImported?.();
    handleClose();
  };

  const handleClose = () => {
    setRows([]);
    setFileName('');
    setProgress(0);
    onClose();
  };

  return (
    <Modal open={open} onClose={handleClose} title="Bulk Import Properties" width="max-w-2xl">
      <div className="space-y-4">
        <p className="text-sm text-ink-muted">
          Import properties from the <code className="text-xs bg-surface-hover px-1.5 py-0.5 rounded">manifest.csv</code> generated by the
          folder-organizing script. This only creates the property entries (name, location, type, furnishing, price) - no photos or
          videos are attached. Add those afterward from each property's "Add Media" section.
        </p>

        {!fileName ? (
          <label className="flex flex-col items-center justify-center gap-2 border-2 border-dashed border-surface-border rounded-xl py-10 cursor-pointer hover:border-accent/40 hover:bg-surface-hover transition-colors">
            <Upload size={22} className="text-ink-faint" />
            <span className="text-sm text-ink-muted">Click to choose your manifest.csv</span>
            <input type="file" accept=".csv" className="hidden" onChange={handleFile} />
          </label>
        ) : (
          <div className="flex items-center gap-2 text-sm text-ink">
            <FileSpreadsheet size={16} className="text-accent" />
            {fileName}
            <button onClick={() => { setRows([]); setFileName(''); }} className="text-xs text-accent hover:underline ml-2">
              Choose a different file
            </button>
          </div>
        )}

        {rows.length > 0 && (
          <>
            <div className="flex items-center gap-4 text-sm">
              <span className="flex items-center gap-1.5 text-success"><Check size={14} /> {validRows.length} ready to import</span>
              {skippedCount > 0 && (
                <span className="flex items-center gap-1.5 text-amber"><AlertTriangle size={14} /> {skippedCount} skipped (no name)</span>
              )}
            </div>

            <div className="max-h-64 overflow-y-auto border border-surface-border rounded-xl">
              <table className="w-full text-xs">
                <thead className="sticky top-0 bg-surface">
                  <tr className="text-left text-ink-muted border-b border-surface-border">
                    <th className="px-3 py-2">Name</th>
                    <th className="px-3 py-2">Location</th>
                    <th className="px-3 py-2">Type</th>
                    <th className="px-3 py-2">Furnishing</th>
                    <th className="px-3 py-2">Price</th>
                  </tr>
                </thead>
                <tbody>
                  {validRows.map((r, i) => (
                    <tr key={i} className="border-b border-surface-border/60">
                      <td className="px-3 py-1.5 text-ink">{r.name}</td>
                      <td className="px-3 py-1.5 text-ink-muted">{r.location || '—'}</td>
                      <td className="px-3 py-1.5 text-ink-muted">{r.propertyType || '—'}</td>
                      <td className="px-3 py-1.5 text-ink-muted">{r.furnishing || '—'}</td>
                      <td className="px-3 py-1.5 text-ink-muted">{r.priceRange || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="secondary" onClick={handleClose}>Cancel</Button>
          <Button onClick={handleImport} disabled={!validRows.length} loading={importing}>
            {importing ? `Importing ${progress}/${validRows.length}...` : `Import ${validRows.length || ''} Properties`}
          </Button>
        </div>
      </div>
    </Modal>
  );
}
